version: '2'
services:
  bot:
    image: hexeo/hbot
    build: .
    command: npm run dev
    volumes:
      - ./tsconfig.json:/opt/tsconfig.json
      - ./package.json:/opt/package.json
      - ./package-lock.json:/opt/package-lock.json
      - ./config:/opt/config
      - ./src:/opt/src
      - ./tests:/opt/tests
